#ifndef EVENTS
#define EVENTS

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(ADA_APP_EVENT_BASE);

typedef enum
{
    ADA_DEVICE_ENABLED,
    ADA_DEVICE_SHUTDOWN,

    ADA_SERVER_CONNECTION_LOST,
    ADA_SERVER_CONNECTION_ESTABLISHED,

    ADA_CONFIG_CHANGED,

    ADA_WAKE_WORD_DETECTED,
    ADA_WAKE_WORD_DETECTION_STARTED,
    ADA_WAKE_WORD_DETECTION_STOPPED,

    ADA_COMMAND_RECORDING_STARTED,
    ADA_COMMAND_RECORDING_STOPPED,
} ada_app_event_t;

#endif /* EVENTS */
