#ifndef ADA_GLOBAL_EVENTS
#define ADA_GLOBAL_EVENTS

#include "string"
#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(ADA_APP_EVENT_BASE);

typedef enum
{
    // DEVICE
    APP_EVENT_DEVICE_READY,
    APP_EVENT_DEVICE_SHUTDOWN_REQUESTED,

    // CONFIG
    APP_EVENT_SETTINGS_CHANGE_REQUESTED,
    APP_EVENT_SETTINGS_CHANGED,

    // BLE GATT SETUP
    APP_EVENT_BLE_DEV_CONNECTED,
    APP_EVENT_BLE_DEV_DISCONNECTED,
    APP_EVENT_BLE_AUTH_CMPL,
    APP_EVENT_BLE_SETUP_DATA_RECEIVED,
    APP_EVENT_BLE_SETUP_FINISH_REQ,

    // WIFI
    APP_EVENT_WIFI_CONNECTED,
    APP_EVENT_WIFI_CONNECTION_FAILED,
    APP_EVENT_WIFI_DISCONNECTED,

    // PAIRING
    ADA_EVENT_PAIRING_STARTED,
    APP_EVENT_PAIRING_COMPLETED,

    // SERVER CONNECTION
    APP_EVNET_SERVER_CONNECTION_LOST,
    APP_EVENT_SERVER_CONNECTION_ESTABLISHED,

    // WAKE WORD
    APP_EVENT_WAKE_WORD_DETECTED,
    APP_EVENT_WORD_DETECTION_STARTED,
    APP_EVENT_WAKE_WORD_DETECTION_STOPPED,

    // COMMAND RECORDING
    APP_EVENT_COMMAND_RECORDING_STARTED,
    APP_EVENT_COMMAND_RECORDING_CHUNK_READY,
    APP_EVENT_COMMAND_RECORDING_FINISHED,
    APP_EVENT_COMMAND_RESPONSE_RECEIVED,
    APP_EVENT_COMMAND_RESPONSE_ERROR
} ada_app_event_t;

#endif /* ADA_GLOBAL_EVENTS */
